In [382]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [383]:
array1d = np.array([12.23,13.32,100.0, 36.32])
print(array1d)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [384]:
array2 = np.arange(2,11)
array2 = array2.reshape(3,3)
print(array2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.


[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [385]:
nulls = np.zeros(10)
print(nulls)
nulls[6] = 11
print(nulls) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [386]:
Original_array= [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]

print(Original_array[::-1])


[37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

In [387]:
ones_array = np.ones(25)
# ones_array=ones_array.reshape(5,5)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [388]:
zeros_arr = np.zeros(9)
zeros_arr=zeros_arr.reshape(3,3)
zeros_arr = np.pad(zeros_arr, pad_width = 1, constant_values = 1)
print(zeros_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [389]:
ones_array[6:19] = 0

In [390]:
ones_array[10] = 1
ones_array[9] = 1
ones_array[14] = 1
ones_array[15] = 1


ones_array = ones_array.reshape(5,5)
print(ones_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [391]:
arr = np.ones((3,3))
print(arr)
arr = np.pad(arr, pad_width=1,constant_values=0)

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [392]:

# Your original array
arr = np.array([[0., 0., 0., 0., 0.],
                [0., 1., 1., 1., 0.],
                [0., 1., 1., 1., 0.],
                [0., 1., 1., 1., 0.],
                [0., 0., 0., 0., 0.]])

arr = arr[1:-1, 1:-1]

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [393]:
Original_array1 = np.ones(9)
Original_array1 = Original_array1.reshape(3,3)
Original_array1 = np.pad(Original_array1,pad_width=1,constant_values=0)
print(Original_array1)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [394]:
checkerboard = np.zeros((8,8),dtype=int)

checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [395]:
Original_array2 = np.zeros((3,3))
Original_array2[(0,0)] = 1
Original_array2[(1,1)] = 1
Original_array2[(2,2)] = 1
print(Original_array2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]


In [396]:
Original_array3 = np.zeros((4,3))
Original_array3[3] = 1 
Original_array3[(1,0)] = 1
Original_array3[(2,0)] = 1
Original_array3[(2,1)] = 1

print(Original_array3)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [397]:
Original_array_elements = np.array([[ 0, 1, 2 ,3],[ 4, 5, 6, 7],[ 8, 9, 10, 11]])
Original_array_elements = Original_array_elements[0:3] * 3
print(Original_array_elements)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [398]:
Original_array_elements1=np.array([[0, 1],[2, 3],[4, 5]])

Original_array_elements1 = Original_array_elements1.ravel()
print(Original_array_elements1)

[0 1 2 3 4 5]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [399]:
a= np.array([1, 2])
b= np.array([4, 5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)


[False False]
[False False]
[ True  True]
[ True  True]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [400]:
Original_array4=np.array([[10 ,20 ,30],[20, 40, 50]])
Original_array4 = Original_array4.ravel()
print(Original_array4)

[10 20 30 20 40 50]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [401]:
Original_array5 = np.zeros((3,3,3))
Original_array5[(0,0,0)] = 1
Original_array5[(0,1,1)] = 1
Original_array5[(0,2,2)] = 1

Original_array5[(1,0,0)] = 1
Original_array5[(1,1,1)] = 1
Original_array5[(1,2,2)] = 1

Original_array5[(2,0,0)] = 1
Original_array5[(2,1,1)] = 1
Original_array5[(2,2,2)] = 1

print(Original_array5)


[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [402]:
Original_array6 = np.array([[ 2, 4, 6],[ 6, 8, 10]],dtype=np.int32)

Original_array6 = Original_array6.astype(dtype=np.float64)

print(Original_array6)

[[ 2.  4.  6.]
 [ 6.  8. 10.]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]


In [403]:
Original_array7 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
Original_array7 = np.delete(Original_array7, [0,3,4])
print(Original_array7)

[ 20  30  60  70  80  90 100]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]


In [404]:
Original_array8 = np.array([[ 10, 20, 30],[ 40, 50, 60]])

adders = np.array([[100],[200]])

result = np.append(Original_array8,adders,axis=1)
print(result)

[[ 10  20  30 100]
 [ 40  50  60 200]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [431]:
arr = np.array([[0, 1], [2, 3], [4, 5]])
list_structure = arr.tolist()
print(list_structure)

[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [436]:
arrayy = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
                0.35399976, 0.99469633, 0.0694458, 0.54711478])

list_structure1 = arrayy.tolist()

np.set_printoptions(precision=3)



print(arrayy)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [439]:
# 21. Write a Python program to make an array immutable (read-only).
# Expected Output:
# Test the array is read-only or not:
# Try to change the value of the first element:
# Traceback (most recent call last):
# File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
# x[0] = 1
# ValueError: assignment destination is read-only

arrayy1 = np.array([0, 1, 2, 3, 4])
arrayy1.flags.writeable = False



[[ 10  20  30 100]
 [ 40  50  60 200]]


In [443]:
# 19. Write a Python program to create an array which looks like below array.
# Expected Output:
# [[ 0. 0. 0.]
# [ 1. 0. 0.]
# [ 1. 1. 0.]
# [ 1. 1. 1.]]

arrayy2 = np.tri(4,3,-1)
print(arrayy2)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
