In [6]:
import numpy as np

In [5]:
my_array1 = np.array([1,5,3], np.int8)
print(my_array1)

[1 5 3]


In [7]:

arr = np.array([5,6,7], np.int8)
print(arr)
print(arr[1])

[5 6 7]
6


In [8]:
arr2 = np.array([[1,6,3],[4,7,8],[9,7,8]])
arr3= np.array([[[9,7,5],[7,5,1],[6,4,5]]])

print(arr2)
print(arr2[2,1])
print(arr2[2])

print(arr.shape) #1D array with 3 length
print(arr2.shape) #2d array with 3 columns and 3 rows

[[1 6 3]
 [4 7 8]
 [9 7 8]]
7
[9 7 8]
(3,)
(3, 3)


In [10]:

zeros = np.zeros([3,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
range = np.arange(10)
print(range)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
lspace = np.linspace(1,10,2)
print(lspace)

print(arr2.T)
print(arr3.ndim)

[ 1. 10.]
[[1 4 9]
 [6 7 7]
 [3 8 8]]
3


In [13]:
arr4 = np.array([[1,9],[4,6],[2,5]])
print(arr4)
arr4 = arr4.reshape(2,3)
print(arr4)

[[1 9]
 [4 6]
 [2 5]]
[[1 9 4]
 [6 2 5]]


In [19]:
print(np.loadtxt('text.txt'))

2322.2323


In [20]:
print(arr2.ravel())

[1 6 3 4 7 8 9 7 8]


In [33]:
arrays = np.array([6,5,7,9,4,2,5,7,8,4,2,5,8])

print(arrays == 8)
print(arrays < 0)
print(arrays > 5)

[False False False False False False False False  True False False False
  True]
[False False False False False False False False False False False False
 False]
[ True False  True  True False False False  True  True False False False
  True]


In [36]:
print(arrays[arrays>7])

[9 8 8]


In [39]:
arr2[:,2]

array([3, 8, 8])

In [41]:
array1 = np.array([[6,9,8,7],[1,7,2,3],[4,2,1,6]])
print(array1)

[[6 9 8 7]
 [1 7 2 3]
 [4 2 1 6]]


In [43]:
#replacing an element in an array using slicing
array1[1,2] = 5
print(array1)

[[6 9 8 7]
 [1 7 5 3]
 [4 2 1 6]]


In [48]:
print(array1.size)

12


In [55]:
#3d arrays
arr3d = np.array([[[1,5,6],[4,0,3]],[[4,6,9],[6,7,1]]])
print(arr3d)

[[[1 5 6]
  [4 0 3]]

 [[4 6 9]
  [6 7 1]]]


In [101]:
print(arr3d[0,1,1])
print(arr3d[1,1,2])

0
1
